### ISSUE TITLE
errors in console

### ISSUE THREAD

**Issue by an303042** [Gerschel/sd-web-ui-quickcss#5]
Hey,
I really love this extension, and I will say everything seems to be working fine, but I am getting lots of errors in the console and its messing with my head.
```

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "F:\SD\stable-diffusion-webui\modules\api\api.py", line 80, in log_and_time
    res: Response = await call_next(req)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 80, in call_next
    raise app_exc
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 334, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path F:\SD\stable-diffusion-webui\logo.png does not exist.

```

Any help would be appreciated!

**Comment by Gerschel** [comment]
Try setting a logo. I think the current version of the css files call for a logo. We didn't think to exclude it.  
There should be one available in the dropdown. It will apply them on the buttons, and as a background image in the gallery.  
It doesn't have to be the png in that folder, it could technically be a jpeg as well, and there is an import section, and when the file explorer pops up, it doesn't have to be a local file, it could be a web address.  

Using the apply logo button will assign a copy of the image as logo.png, which will fill the issue with this error statement.  

>F:\SD\stable-diffusion-webui\logo.png does not exist.  

I have been away, I'll be making some updates soon. If you don't want a logo in those positions, there is a blank png in the backgrounds folder of the extension you can use, it's 1 px transparent.  Keep me posted. There's a chance a recent update to the main app changed something, I doubt it, but I'm not up to date at the moment.


Location of dropdown about center:
![image](https://user-images.githubusercontent.com/9631031/212641878-3f8e3c58-1b84-4b8b-bb7d-427184b74204.png)  


Location of importing, in the accordion just below the first buttons, it unfolds:
![image](https://user-images.githubusercontent.com/9631031/212642021-761145f2-e78c-4f5e-b456-af181bcdfaf3.png)  



For you, the path to the blankbackground.png should be:
`F:\SD\stable-diffusion-webui\extensions\sd-web-ui-quickcss\backgrounds\blankbackground.png`  

After importing, it will be available in the dropdown, you don't need to hit the download button, that's a gradio thing they added in case a user was remote.  

What it looks like after an import:
![image](https://user-images.githubusercontent.com/9631031/212643075-6237a797-fc61-4061-a1f0-df1dd8c25595.png)

**Comment by an303042** [comment]
Wow, thanks for the super detailed reply.
I'll admit I do feel a little bad making you post such a detailed reply with screenshots and everything when all that was needed was to apply the logo. 😊
Thanks again for you work and helpfulness!

**Comment by Gerschel** [comment]
It's fine. It provides documented solutions for others that may run across the situation, or an edge case situation.
